# Use root/example as user/password credentials

services:
  mongo:
    image: mongo:7.0.12
    volumes:
        - mongo-orion-domain:/data/db
    restart: always
  orion:
    image: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/orion-ld:1.1.1
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo -mongocOnly -brokerId broker1 -forwarding -wip entityMaps,distSubs -t 70-99 -logLevel DEBUG -disableFileLog -noArrayReduction
    restart: always
volumes:
  mongo-orion-domain:

